### ISSUE TITLE
Issue: Unable to write to SQLite database

### ISSUE THREAD

**Issue by Whizma** [JoysOfCode/sveltekit-auth-cookies#11]
**Issue: Unable to write to SQLite database**

When trying to register a user in my SvelteKit app with Prisma and SQLite, I receive the following error:

``` 
Invalid `prisma.user.create()` invocation:

Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: 
QueryError(SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, 
Some("attempt to write a readonly database"))), transient: false })
```

I have already tried giving write permissions to both the database and the folder, but the error persists.

**Steps to reproduce:**

Try to register a new user in the SvelteKit app
Observe the error in the console

**Expected behavior:**

The user should be successfully registered and added to the SQLite database.

**Code**

/register/+page.server.ts looks like:
```
import { fail, redirect } from '@sveltejs/kit'
import bcrypt from 'bcrypt'

import db from '../../../lib/userDatabase';

// using an enum for user roles to avoid typos
// if you're not using TypeScript use an object
enum Roles {
	ADMIN = 'ADMIN',
	USER = 'USER',
}

export const load = async ({ locals }) => {
	// redirect user if logged in
	if (locals.user) {
		throw redirect(302, '/')
	}
}

export const actions = {
	register: async ({ request }) => {
		const data = await request.formData()
		const username = data.get('username')
		const password = data.get('password')
		console.log("request: " + request);

		if (
			typeof username !== 'string' ||
			typeof password !== 'string' ||
			!username ||
			!password
		) {
			return fail(400, { invalid: true })
		}
		const user = await db.user.findUnique({
			where: { username },
		})

		if (user) {
			return fail(400, { user: true })
		}

		await db.user.create({
			data: {
				username,
				passwordHash: await bcrypt.hash(password, 10),
				userAuthToken: crypto.randomUUID(),
				role: { connect: { name: Roles.USER } },
			}, 
		})
		console.log("data: " + data);
		throw redirect(303, '/login')
	},
}
```

**Environment:**

OS: EndeavourOS 6.2.9
NodeJS: 19.8.1
SQLite: 3.41.2
Prisma: 4.12.0
Sveltekit: 1.15.2

**Comment by matiadev** [comment]
@Whizma I tried it out and everything works fine!

I assume you followed the steps including creating the user roles, so it must be an issue with permissions. I'm also using Linux by the way and I never got this issue before. Try nuking everything and doing it again and make sure it's not permissions.

I'm going to close the issue because I can't recreate it but if you need help in the future you can [ask for help on Discord](https://joyofcode.xyz/invite).
