### ISSUE TITLE
seems simple yet it's not

### ISSUE THREAD

**Issue by secretgspot** [JoysOfCode/sveltekit-auth-cookies#7]
Is it possible to make an example that connects to supabase instead of prism to set hooks and session. I've tried to adjust but all to no avail

**Comment by matiadev** [comment]
> Is it possible to make an example that connects to supabase instead of prism to set hooks and session. I've tried to adjust but all to no avail.

Prisma doesn't care what database you use as long as it's supported. You can create a PostgreSQL database in Supabase and change the Prisma configuration to use `postgresql` and the connection string in `.env` and everything should work fine https://supabase.com/docs/guides/integrations/prisma.
