### ISSUE TITLE
Invalid request body

### ISSUE THREAD

**Issue by KoljaL** [JoysOfCode/sveltekit-auth-cookies#8]
Thanks a lot for this example!

After the installation process, i tried to register myself (yes, i added the user-roles) and got an `internal server error` with the response `invalid request body`.

After a short research, i found this:
#https://github.com/sveltejs/kit/issues/5370

And updated the `sveltejs/kit`in the `package.json` from `.504` to the current version `.560` and run the installation again.

Now it works

**Comment by arunabhdas** [comment]
Was there any solution for this issue?

I am still getting this error 

`Invalid request body`

in svelteKit 1.0

as of Dec 22, 2022

My server.js has a function that looks as below -

```
export async function POST({ request }) {
    const body = await request.json()
    console.log(body)
    return new Response(JSON.stringify({message: "Success"}), {status: 201})

}

```

**Comment by matiadev** [comment]
Thank you! 😄
