### ISSUE TITLE
Update to Kit 1.0

### ISSUE THREAD

**Issue by myhrmans** [JoysOfCode/sveltekit-auth-cookies#9]
Now that version 1.0 is stable and released this would be lovely to have with the latest version of Sveltekit. 

I know this was requested before in #2, but would be lovely if time is available. Gave it a try without success.

**Comment by matiadev** [comment]
This is based on the latest version of SvelteKit.

**Comment by trasherdk** [comment]
:roll_eyes: No, not even close.

```
 @prisma/client                            ^4.3.1  →  ^4.10.1
 @sveltejs/adapter-auto             1.0.0-next.80  →    2.0.0
 @sveltejs/kit                     1.0.0-next.504  →    1.8.5
 @typescript-eslint/eslint-plugin         ^5.38.1  →  ^5.53.0
 @typescript-eslint/parser                ^5.38.1  →  ^5.53.0
 bcrypt                                    ^5.0.1  →   ^5.1.0
 eslint                                   ^8.24.0  →  ^8.34.0
 eslint-config-prettier                    ^8.5.0  →   ^8.6.0
 prettier                                  ^2.7.1  →   ^2.8.4
 prettier-plugin-svelte                    ^2.7.1  →   ^2.9.0
 svelte                                   ^3.50.1  →  ^3.55.1
 svelte-check                              ^2.9.1  →   ^3.0.4
 svelte-preprocess                        ^4.10.7  →   ^5.0.1
 tslib                                     ^2.4.0  →   ^2.5.0
 typescript                                ~4.8.3  →   ~4.9.5
 vite                                      ^3.1.3  →   ^4.1.4
```

**Comment by matiadev** [comment]
@trasherdk This is meant to be educational and being condescending doesn't help. Please be more considerate and ask because what I said meant that the SvelteKit API didn't change enough to warrant upgrading the dependencies.

**Comment by trasherdk** [comment]
I'm sorry if I came of like that. Not my intention.

Still, this code does not run on current sveltekit versions.

**Comment by matiadev** [comment]
I updated the project to the latest version of SvelteKit #10.
